version: '2'
services:
  server:
    environment:
      - 'PORT=3000'
    # Pointing at my working docker image
    image: 'stefanv15/tictactoe:${GIT_COMMIT}'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
  postgres:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    ports:
      - "5432:5432"
